site_name: RADocs 
site_description: RetroAchievements.org Documentation Project 
site_url: https://docs.retroachievements.org/

repo_name: RetroAchievements/docs
repo_url: https://github.com/RetroAchievements/docs/wiki/
# XXX: If you do not want any "edit URL link" displayed on your pages,
# then set edit_uri to an empty string to disable the automatic setting.
edit_uri: https://retroachievements.org/wiki-edit-redirect.php?page=

docs_dir: docs.wiki

theme:
    name: material
    features:
       - navigation.tabs
       - navigation.instant
    palette:
        primary: 'indigo'
        accent: 'amber'
    icon:
      logo: fontawesome/solid/gamepad
      repo: fontawesome/brands/github
    favicon: 'img/favicon.ico'

markdown_extensions:
    - toc:
        permalink: link
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.tilde

extra:
    social:
        - icon: fontawesome/solid/globe
          link: https://retroachievements.org/
        - icon: fontawesome/brands/discord
          link: https://discord.gg/dq2E4hE
        - icon: fontawesome/brands/github
          link: https://github.com/RetroAchievements

plugins:
    - alternate-link
    - search:
        separator: '[\s\-\.]+'
        lang:
          - en
          - pt
          - es

# strict 
# Determines if a broken link to a page within the documentation is considered 
# a warning or an error (link to a page not listed in the pages setting). Set 
# to true to halt processing when a broken link is found, false prints a warning 
#strict: true

# dev_addr 
# Determines the address used when running mkdocs serve. 
# Must be of the format IP:PORT. 
dev_addr: '127.0.0.1:8000'
